package com.timmy.github_silkrode.api

import com.google.gson.annotations.SerializedName

data class UserInfo(
    @SerializedName("login") val login: String,
    @SerializedName("id") val id: Int,
    val nodeId: String,
    @SerializedName("avatar_url") val avatarUrl: String,
    @SerializedName("gravatar_id") val gravatarId: String,
    val url: String,
    val htmlUrl: String,
    val followersUrl: String,
    val followingUrl: String,
    val gistsUrl: String,
    val starredUrl: String,
    val subscriptionsUrl: String,
    val organizationsUrl: String,
    val reposUrl: String,
    val eventsUrl: String,
    val receivedEventsUrl: String,
    val type: String,
    val siteAdmin: String,
    @SerializedName("name") val name: String,
    val company: String,
    val blog: String,
    val location: String,
    @SerializedName("email") val email: String,
    val hireable: String,
    val bio: String,
    val publicRepos: Int,
    val publicGists: Int,
    @SerializedName("followers") val followers: Int,
    @SerializedName("following") val following: Int,
    val createdAt: String,
    val updatedAt: String,
    val privateGists: Int,
    val totalPrivateRepos: Int,
    val ownedPrivateRepos: Int,
    val diskUsage: Int,
    val collaborators: Int,
    val twoFactorAuthentication: Boolean
)
